export interface Article {
    Name: string,
    'Closet Image': string,
    'Storage Image': string,
    Variation: string,
    DIY: string,
    Buy: string,
    Sell: number,
    'HHA Base Points': number,
    'Color 1': string,
    'Color 2': string,
    Size: string,
    'Miles Price': string,
    Source: string,
    'Source Notes': string,
    'Seasonal Availability': string,
    'Mannequin Piece': string,
    Style: string,
    'Sort Order': number,
    'Label Themes': string,
    Type: string,
    'Villager Equippable': string,
    Catalog: string,
    'Version Added': string,
    'Version Unlocked': string,
    Filename: string,
    'ClothGroup ID': number,
    'Internal ID': number,
    'Unique Entry ID': string
}